 create table student_course_details (
        id integer generated by default as identity,
        course_id integer,
        student_id integer,
        primary key (id)
    );
      create table student (
            id integer generated by default as identity(start with 1000),
            email varchar(255),
            first_name varchar(255),
            last_name varchar(255),
            primary key (id)
        );
        create table lecture (
                id integer generated by default as identity(start with 1000),
                description varchar(255),
                lecture_order integer not null,
                title varchar(255),
                course_id integer,
                primary key (id)
            );
            create table course (
                    id integer generated by default as identity(start with 1000),
                    code varchar(255) not null,
                    name varchar(255) not null,
                    primary key (id)
                );
            alter table if exists course add constraint UKi60mruj0y7a7vs99dqpiye7en unique (code);